- hosts: public
  become: yes
  tasks:
          - name: "reverse proxy"
            user:
                    name: public
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/public

- hosts: frontend
  become: yes
  tasks:
          - name: "fe"
            user:
                    name: fe
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/fe

- hosts: frontend2
  become: yes
  tasks:
          - name: "fe2"
            user:
                    name: fe2
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/fe2

- hosts: backend
  become: yes
  tasks:
          - name: "be"
            user:
                    name: backend
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/be

- hosts: backend2
  become: yes
  tasks:
          - name: "be2"
            user:
                    name: backend2
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/be2

- hosts: database
  become: yes
  tasks:
          - name: "db"
            user:
                    name: db
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/db

- hosts: database2
  become: yes
  tasks:
          - name: "db2"
            user:
                    name: db2
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/db2

- hosts: jenkins
  become: yes
  tasks:
          - name: "jk"
            user:
                    name: jk
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    ssh_key_comment: mufid@dumbways
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/jk

- hosts: monitor
  become: yes
  tasks:
          - name: "mt"
            user:
                    name: monitoring
                    password: "$6$K2jls9klg/n$6P2fTb9itMKRsUUFP7J5MDSS.AbBRb09DLaqVoqUw14Xu9ZqxGcxVNX9W9zcNltJgG8r9iprIlMqG/MNuvdmz1"
                    groups: sudo,docker
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/mt
                                        
# Change PasswordAuthentication and reload sshd
- hosts: all
  become: yes
  tasks:
          - name: change PasswordAuth
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: 'PasswordAuthentication no'
                    line: PasswordAuthentication yes

          - name: reload sshd
            systemd:
                    name: sshd
                    state: reloaded
